package com.yuxh.blog.model;

import java.util.Date;

public class BlogInfo {

    private String typeName;
    private Integer pageViewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.blog_id
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    private Integer blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.blog_title
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    private String blogTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.blog_abstract
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    private String blogAbstract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.blog_author
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    private String blogAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.create_date
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.type_id
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.lable_name
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    private String lableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.blog_cover
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    private String blogCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.top_switch
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    private Integer topSwitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.recommend_switch
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    private Integer recommendSwitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.blog_uuid
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    private String blogUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.blog_context
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    private String blogContext;


    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public Integer getPageViewCount() {
        return pageViewCount;
    }

    public void setPageViewCount(Integer pageViewCount) {
        this.pageViewCount = pageViewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.blog_id
     *
     * @return the value of blog_info.blog_id
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.blog_id
     *
     * @param blogId the value for blog_info.blog_id
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.blog_title
     *
     * @return the value of blog_info.blog_title
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.blog_title
     *
     * @param blogTitle the value for blog_info.blog_title
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle == null ? null : blogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.blog_abstract
     *
     * @return the value of blog_info.blog_abstract
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public String getBlogAbstract() {
        return blogAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.blog_abstract
     *
     * @param blogAbstract the value for blog_info.blog_abstract
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public void setBlogAbstract(String blogAbstract) {
        this.blogAbstract = blogAbstract == null ? null : blogAbstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.blog_author
     *
     * @return the value of blog_info.blog_author
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public String getBlogAuthor() {
        return blogAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.blog_author
     *
     * @param blogAuthor the value for blog_info.blog_author
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public void setBlogAuthor(String blogAuthor) {
        this.blogAuthor = blogAuthor == null ? null : blogAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.create_date
     *
     * @return the value of blog_info.create_date
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.create_date
     *
     * @param createDate the value for blog_info.create_date
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.type_id
     *
     * @return the value of blog_info.type_id
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.type_id
     *
     * @param typeId the value for blog_info.type_id
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.lable_name
     *
     * @return the value of blog_info.lable_name
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public String getLableName() {
        return lableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.lable_name
     *
     * @param lableName the value for blog_info.lable_name
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public void setLableName(String lableName) {
        this.lableName = lableName == null ? null : lableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.blog_cover
     *
     * @return the value of blog_info.blog_cover
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public String getBlogCover() {
        return blogCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.blog_cover
     *
     * @param blogCover the value for blog_info.blog_cover
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public void setBlogCover(String blogCover) {
        this.blogCover = blogCover == null ? null : blogCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.top_switch
     *
     * @return the value of blog_info.top_switch
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public Integer getTopSwitch() {
        return topSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.top_switch
     *
     * @param topSwitch the value for blog_info.top_switch
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public void setTopSwitch(Integer topSwitch) {
        this.topSwitch = topSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.recommend_switch
     *
     * @return the value of blog_info.recommend_switch
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public Integer getRecommendSwitch() {
        return recommendSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.recommend_switch
     *
     * @param recommendSwitch the value for blog_info.recommend_switch
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public void setRecommendSwitch(Integer recommendSwitch) {
        this.recommendSwitch = recommendSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.blog_uuid
     *
     * @return the value of blog_info.blog_uuid
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public String getBlogUuid() {
        return blogUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.blog_uuid
     *
     * @param blogUuid the value for blog_info.blog_uuid
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public void setBlogUuid(String blogUuid) {
        this.blogUuid = blogUuid == null ? null : blogUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.blog_context
     *
     * @return the value of blog_info.blog_context
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public String getBlogContext() {
        return blogContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.blog_context
     *
     * @param blogContext the value for blog_info.blog_context
     *
     * @mbggenerated Wed May 03 15:16:02 CST 2017
     */
    public void setBlogContext(String blogContext) {
        this.blogContext = blogContext == null ? null : blogContext.trim();
    }
}