package com.yuxh.blog.model;

public class LableInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lable_info.lable_id
     *
     * @mbggenerated Wed Mar 22 23:45:13 CST 2017
     */
    private Integer lableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lable_info.lable_name
     *
     * @mbggenerated Wed Mar 22 23:45:13 CST 2017
     */
    private String lableName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lable_info.lable_id
     *
     * @return the value of lable_info.lable_id
     *
     * @mbggenerated Wed Mar 22 23:45:13 CST 2017
     */
    public Integer getLableId() {
        return lableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lable_info.lable_id
     *
     * @param lableId the value for lable_info.lable_id
     *
     * @mbggenerated Wed Mar 22 23:45:13 CST 2017
     */
    public void setLableId(Integer lableId) {
        this.lableId = lableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lable_info.lable_name
     *
     * @return the value of lable_info.lable_name
     *
     * @mbggenerated Wed Mar 22 23:45:13 CST 2017
     */
    public String getLableName() {
        return lableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lable_info.lable_name
     *
     * @param lableName the value for lable_info.lable_name
     *
     * @mbggenerated Wed Mar 22 23:45:13 CST 2017
     */
    public void setLableName(String lableName) {
        this.lableName = lableName == null ? null : lableName.trim();
    }
}