package com.yuxh.blog.dao;

import com.yuxh.blog.model.CommentInfo;

import java.util.List;

public interface CommentInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Thu Mar 23 20:44:10 CST 2017
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Thu Mar 23 20:44:10 CST 2017
     */
    int insert(CommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Thu Mar 23 20:44:10 CST 2017
     */
    int insertSelective(CommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Thu Mar 23 20:44:10 CST 2017
     */
    CommentInfo selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Thu Mar 23 20:44:10 CST 2017
     */
    int updateByPrimaryKeySelective(CommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Thu Mar 23 20:44:10 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Thu Mar 23 20:44:10 CST 2017
     */
    int updateByPrimaryKey(CommentInfo record);

    List<CommentInfo> getByBlogId(String blogId);
}