package com.yuxh.blog.dao;

import com.yuxh.blog.model.LableInfo;

public interface LableInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lable_info
     *
     * @mbggenerated Wed Mar 22 23:45:13 CST 2017
     */
    int deleteByPrimaryKey(Integer lableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lable_info
     *
     * @mbggenerated Wed Mar 22 23:45:13 CST 2017
     */
    int insert(LableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lable_info
     *
     * @mbggenerated Wed Mar 22 23:45:13 CST 2017
     */
    int insertSelective(LableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lable_info
     *
     * @mbggenerated Wed Mar 22 23:45:13 CST 2017
     */
    LableInfo selectByPrimaryKey(Integer lableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lable_info
     *
     * @mbggenerated Wed Mar 22 23:45:13 CST 2017
     */
    int updateByPrimaryKeySelective(LableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lable_info
     *
     * @mbggenerated Wed Mar 22 23:45:13 CST 2017
     */
    int updateByPrimaryKey(LableInfo record);
}